### ISSUE TITLE
Provide better error messages if the maximum number of audiocontexts are reached/will be reached

### ISSUE THREAD

**Issue by CYDP0127** [katspaugh/wavesurfer.js#1005]
Hi there, I have a question.

I am getting this error below when I am creating multiple waveforms

Uncaught DOMException: Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6).

here's my code

```
for(var i =0; i < 10; i++){
    var wavesurfer = WaveSurfer.create({
        container: '#waveform-0',
        waveColor: 'red',
        progressColor: 'purple',
        hideScrollbar: true
    });
    wavesurfer.load('audio.mp3');
}
```

And My guess was it's because I am creating multiple instance but I found that it occurs error when I use the newest version (1.3.2) and it works without error when I use an old one(1.0.52)

If it's not a bug, can someone let me know how to create multiple waveforms in a right way ??

**Comment by mspae** [comment]
Hello @CYDP0127 – The issue you're experiencing is probably due to https://github.com/katspaugh/wavesurfer.js/pull/862 (Don't reuse the audiocontext in `WaveSurfer.WebAudio.audioContext` automatically, instead use the `audioContext` provided in the options (`params.audioContext`) or create a new one (and close it when wavesurfer is destroyed)).

Maybe one of these would solve your issues:
* Cache the `audioContext` and pass as parameter to the new wavesurfer instances
* Decode the audio (on the server or wherever), cache the peak data and use the media element backend
* Use one wavesurfer instance to successively load all the audio, decode them, save the peak data and then create the other wavesurfer instances with media element and explicitly set peak data. (That way you only have one audiocontext)

**Comment by entonbiba** [comment]
@CYDP0127 chrome only supports up to 6 audiocontexts, this is fine since it protects the browser from eating up all the CPU. You can try the media element solution as suggested by @mspae with pre-rendered peaks.

**Comment by thijstriemstra** [comment]
Perhaps a meaningful error should be thrown when this maximum is (about to be) reached (if possible?).

**Comment by katspaugh** [comment]
@mspae why did we remove the singleton audio-context? Why creating it every time?

**Comment by mspae** [comment]
@CYDP0127 The limit should not be reached anymore with the new changes merged into master (see above) – This should be fixed with the next release.
