### ISSUE TITLE
Creating multiple waveforms and memory leaking

### ISSUE THREAD

**Issue by CYDP0127** [katspaugh/wavesurfer.js#1034]
Hi, I have a question

I am creating multiple waveforms and it works well by creating one instance and using MediaElement (thanks for people who helped it out #1005)

But I found that there's memory leaking  

Got this from Chrome Timeline and apparently it happens when it calls XHRhttpRequest
![image](https://cloud.githubusercontent.com/assets/13328846/23603955/6da31aea-029a-11e7-9446-49b912496ab1.png)

And this from Chrome profile
![image](https://cloud.githubusercontent.com/assets/13328846/23604433/39b58586-029c-11e7-92c7-1bf1ad8f695e.png)

here's the code from wavesurfer.js

```
 ajax: function (options) {
        ...
        var xhr = new XMLHttpRequest();
        xhr.open(options.method || 'GET', options.url, true);
        xhr.responseType = options.responseType || 'json';
        ...
    }
```

what I don't understand is this ajax function calls an audio file (ex. http://localhost/audio/sample.mp3) and my understanding of ajax call is usually some code file.

So my question is
1. why ajax function calls an audio file.
2. the way how to prevent memory leaking or to free used memory

### Browser version(s):
Chrome Version 56.0.2924.87 (64-bit)

**Comment by mspae** [comment]
1. Ajax (aka `XMLHttpRequest`) can be used to fetch all kinds of files. Wavesurfer loads audio with Ajax if 1. Backend Web Audio is used or 2. Peaks are not provided
2. There are several memory leaks which are currently being fixed for version 2 - the one you experience is probably due to `this.arraybuffer` not being nullified in `destroy`.

**Comment by CYDP0127** [comment]
@mspae thanks a lot !!  I nullified this.arraybuffer and it worked !

**Comment by mspae** [comment]
I'll close this for now. The memory leaks will be fixed ASAP - also on Master.

**Comment by rejochandran** [comment]
> @mspae thanks a lot !! I nullified this.arraybuffer and it worked !

Hi @DOOGIE-CHOE 
Please let me know how you nullified it. 
I am using wavesurfer in a function-based component in React

Thanks

**Comment by DOOGIE-CHOE** [comment]
Hi @rejochandran
its been years so i don't remember clearly. but i remember just putting null to this.arraybuffer so that garbage collector can clean up the unused memories.
i believe this issue should be fixed by now as @mspae mentioned ?

**Comment by rejochandran** [comment]
Hi @DOOGIE-CHOE ,

Thanks for the note and I tried this and still got this issue. 
Some of my findings,
1. The issue mostly occurs in Chrome as it does not clear the memory when a wavesurfer instance is destroyed and opening another instance just adds with to the existing memory and hence mounts up
2. The issue seems to be only with `WebAudio`  as backend but I have no other choice as my application requires the user to navigate back and forth to analyze the audio.

Most of the issues are part of #1940 , So hopefully we get this resolved 🙂
and thanks again for your quick response
