### ISSUE TITLE
Broken drawing of raw peaks

### ISSUE THREAD

**Issue by adw1n** [katspaugh/wavesurfer.js#1055]
When the resolution is small enough rendering pre-generated peaks (on the newest version of wavesurfer) is broken.
![broken1](https://cloud.githubusercontent.com/assets/8993001/24680868/e61935f4-1992-11e7-9cff-37d13ae917d0.png)
![broken2](https://cloud.githubusercontent.com/assets/8993001/24680887/eca7979e-1992-11e7-9830-1ddf7f73212e.png)
Once the screen estate is big enough, stuff is back to normal:
![broken3](https://cloud.githubusercontent.com/assets/8993001/24680917/03b8293a-1993-11e7-9670-d8396d4718e4.png)

On wavesurfer version 1.1.1 I had no problems whatsoever:
![working2](https://cloud.githubusercontent.com/assets/8993001/24680945/2d8be2ec-1993-11e7-839d-56cf098b1e62.png)

Browsers:
* FF 47
* Chromium 51.0.2704.79 

Source code of examples:
* broken (wavesurfer 1.3.7)  
http://public.adw1n.com/wavesurfer_issue/broken.html
* same code was working on version 1.1.1  
http://public.adw1n.com/wavesurfer_issue/working.html

**Comment by Jamby93** [comment]
The problem raises whenever you provide more peaks than the canvasWidth.
The drawWave function of Canvas and drawLineToContext function of MultiCanvas has been broken since #924 by @mspae that has changed the rendering loop from looping the entire peaks array to looping only up to "end" or "canvasEnd" respectively which is both cases the canvas width. In this way, the last point drawn x-coordinate is canvasWidth * scale which is less than canvasWidth whenever you have more peaks than pixels.

**Comment by mspae** [comment]
#924 is the v2 port of #909 – v2 hasn't been released yet – not that it matters :)

**Comment by mspae** [comment]
Related? https://github.com/katspaugh/wavesurfer.js/issues/994

**Comment by X-Raym** [comment]
I confirm this issue. V1.2.8 was fine and 1.3.0 is broken.

**Comment by entonbiba** [comment]
closing, will continue on issue #1067 if pr #1072 doesn't fix it 100%
