### ISSUE TITLE
Does wavesurfer work with streaming audio?

### ISSUE THREAD

**Issue by larnold** [katspaugh/wavesurfer.js#107]
Hi,

Does wavesurfer work with streaming audio or does it need to preload the entire mp3 file first?

Thanks,
Luke

**Comment by voronianski** [comment]
+1

**Comment by chinshr** [comment]
What would it take to support streaming in ws?

**Comment by katspaugh** [comment]
What do you guys mean by streaming and why do you want it?

**Comment by jczimm** [comment]
By streaming I meant audio data piped to clients (think IceCast or SHOUTcast).

**Comment by katspaugh** [comment]
I understand what streaming means in terms of audio. I'm asking what you are expecting the waveform of a stream to look like and the purpose of it.

**Comment by jczimm** [comment]
The way I personally think it would look best is as a running waveform (scrolling), adding data to the right as it is received.

**Comment by thijstriemstra** [comment]
Would be cool to support it in the microphone plugin, I'll try to come up with something

**Comment by antferr** [comment]
+1 for streaming via RTSP or HTTP with live555MediaServer

**Comment by Niades** [comment]
>I understand what streaming means in terms of audio. I'm asking what you are expecting the waveform of a stream to look like and the purpose of it.
@katspaugh I think it would be nice to show only a part of waveform - the one that is playing right now, and then animate it to the next part, and repeat forever. I imagine it looking like an oscillograph. 
P.S. Multi-eyed kitties FTW

**Comment by katspaugh** [comment]
Hey @Niades! Nice avatar 😸

Realtime oscillograph-like waveform is actually built into Web Audio. Here's a tutorial: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Visualizations_with_Web_Audio_API

By the way, we do this in the [microphone plug-in](http://wavesurfer-js.org/example/microphone/)—is that the kind of visuals you mean?

**Comment by free2shout** [comment]
Hi @katspaugh 
How is this gong? I need to start playing the audio before the complete download. Is this possible? I generate the waveform and save the data into my DB so I won't have to generate it again. But I still can't display it and play the audio until it is completely downloaded. That is a bad UX. Some consumers are used to skim the audios. By streaming they don't need to wait for five long downloads and they don't need large storage for them (think about mobiles and tablet users)

**Comment by mspae** [comment]
@free2shout You could use the web audio element as an audio source and pass the prerendered peaks so that the audio isn't downloaded completely before the peaks are being drawn (as seen here: https://wavesurfer-js.org/example/audio-element/)

I think there is a little confusion in this thread, so I'll describe three use cases described here as I see them.

1. Display a waveform of a large file before it has been downloaded ( @free2shout ) – This can be done by passing in the peaks data and using the media element (which allows you to play audio before completely downloading it)
2. Render an oscillograph-style in real time like in the [microphone plugin](http://wavesurfer-js.org/example/microphone/)
3. Render a waveform of a (potentially never ending) audio stream where the waveform is being dynamically extended while the audio is playing (either by using peaks data from the client while the audio is being decoded (not sure if this is possible) – or by requesting peaks data from the server and using the media element for actually playing of audio) – This, I think, is currently not possible, but would definitely be really nice.

**Comment by ZachSaucier** [comment]
I created a streamer-type of format using wavesurfer by sending a bunch of short audio clips from the server. On the frontend I received these pieces, aligned a bunch of wavesurfer elements inline, and listened to the stop event in order to know when to play the next section. Let me know if you need more detail.

**Comment by entonbiba** [comment]
@ZachSaucier it would be nice if you can create an example on codepen or something :)

**Comment by ZachSaucier** [comment]
I don't  have a simplified (or working in the same capacity) version due to the official production server being too costly to keep running, but you can look at the JS of [this older version](https://zachsaucier.com/mv/music-generator.html) for a start/structure of the implementation.

**Comment by r01010010** [comment]
+1 to show an incremental waveform as audio is being loaded WITHOUT having to change anything at the backend. It can be perfectly done with the audio api in my opinion.
