### ISSUE TITLE
progressColor not rendered on master for MultiCanvas

### ISSUE THREAD

**Issue by glebm** [katspaugh/wavesurfer.js#1136]
progressColor is no longer rendered on the current master with MultiCanvas.
It does work with the Canvas renderer.

Works on 1.4.0: https://codepen.io/glebm/pen/KqNJwe
Does not work on master: https://codepen.io/glebm/pen/vZybKy

The culprit is https://github.com/katspaugh/wavesurfer.js/pull/1112 @agamemnus

**Comment by agamemnus** [comment]
Oh, I guess that slipped in while I was working on something else. I had
increased the zIndex of both the top elements for the progress wave and the
normal wave but I guess I forgot to decrease it back for the normal wave.

On Jun 16, 2017 6:14 AM, "Gleb Mazovetskiy" <notifications@github.com>
wrote:

progressColor is no longer rendered on the current master with MultiCanvas.
It does work with the Canvas renderer.

Works on 1.4.0: https://codepen.io/glebm/pen/KqNJwe
Does not work on master: https://codepen.io/glebm/pen/vZybKy

I believe the culprit is #1112
<https://github.com/katspaugh/wavesurfer.js/pull/1112> @agamemnus
<https://github.com/agamemnus>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/katspaugh/wavesurfer.js/issues/1136>, or mute the thread

**Comment by agamemnus** [comment]
I added https://github.com/katspaugh/wavesurfer.js/pull/1137 to fix this, although my rework at https://github.com/katspaugh/wavesurfer.js/pull/1132 should make that PR moot...
