### ISSUE TITLE
How to hook into concrete peak value at playback position during playback

### ISSUE THREAD

**Issue by aahedi** [katspaugh/wavesurfer.js#1162]
Is it can do a function like this:

if the _**blue**_ line on low waveform then hide image, else show image.

repeating function on when playing audio

![wave](https://user-images.githubusercontent.com/8935884/28247530-9898b6ae-6a5c-11e7-8eb0-ad36dddf3f0b.jpg)

**Comment by entonbiba** [comment]
@aahedi I wouldn't do that since sometimes the waveform needs to be 0db as there is no audio. You can use the `barHeight` parameter to increase the waveform height within the canvas.

**Comment by aahedi** [comment]
@entonbiba I try this code but not work

`function showImage() {
    var img = document.getElementById('imgku');
    img.style.visibility = 'visible';
}
function hideImage() {
    var img = document.getElementById('imgku');
    img.style.visibility = 'hidden';
}

wavesurfer.on('play', function () {
if (barHeight > 1) {showImage()}
else{hideImage()}
});`

Full source code:
[img-waveform.txt](https://github.com/katspaugh/wavesurfer.js/files/1149910/img-waveform.txt)

**Comment by entonbiba** [comment]
here is an example,
https://codepen.io/entonbiba/pen/VpedWZ

**Comment by aahedi** [comment]
You misunderstood my question. see again my illustration. I mean when the audio is playing, if the position of the line on the low wave then the image is hidden else if high wave then image displayed.

My code: [https://github.com/katspaugh/wavesurfer.js/files/1149910/img-waveform.txt](url)

![waveform](https://user-images.githubusercontent.com/8935884/28243924-40a1591c-6a05-11e7-872e-6cc989a9de11.png)

**Comment by mspae** [comment]
@aahedi Currently this isn't supported. You would implement this by providing an event listener to the `audioprocess` event (exists) – this event would need to be fired with the current peak value as an argument (doesn't exist)

Since this event doesn't get the current peak value (it gets the playback position as a floating point number) you would need to a) get the peak data from wavesurfer (e.g. `exportPCM`) and b) calculate the correct index to get the value of the current playback position.

Something like this (untested!)

```javascript
var peaks;
var ws = WaveSurfer.create({
  // ...
});

ws.on('ready', function() {
  peaks = ws.exportPCM(1024);

  ws.on('audioprocess', function(pos) {
    var currentVal = peaks[Math.round((peaks.length / 2) * pos)];
    console.log('current value is ' + currentVal);
  });
});
```

**Comment by nkli** [comment]
current peak value is wrong
