### ISSUE TITLE
Need Angular 2 or 4 Wrapper Package

### ISSUE THREAD

**Issue by logavdm** [katspaugh/wavesurfer.js#1253]
# Hey, thank you for testing and contributing to wavesurfer.js!

Hi team,

Nice Work team and big thanks for the valuable package. 

I would like to use wavesurfer.js package with angular2 typescript but i con't find any typescript wrapper for this package and also i don't know how to write a wrapper for wavesurfer.
please contribute for this area because many of them use full when you will give a typescript wrapper.

**Comment by thijstriemstra** [comment]
@logavdm can you at least add a ticket description?

**Comment by logavdm** [comment]
Thanks for the reply @thijstriemstra now i added the description

**Comment by mspae** [comment]
From the description it shounds like you need typescript typings, not an Angular 2+x component. This issue is already being discussed in #1209

**Comment by thijstriemstra** [comment]
so it's a duplicate?

**Comment by mspae** [comment]
@logavdm – So Angular and typescript are two seperate things. Typescript is a superset of javascript which is used by Angular, but also by lots of other projects.

- There is an issue to discuss adding typescript typings in #1209
- There recently was an issue asking for an Angular component for wavesurfer in #1200 (The issue was closed because the issue opener didn't react (no pun intended))

I'll close this issue since it isn't clear from your description what you mean.
- If you're just referring to the typescript aspect please comment on #1209
- If you just want to discuss to create an Angular component for wavesurfer you can create a new issue. Bear in mind though that creating and maintaining this component would be a seperate project from the wavesurfer core library.

Also note that you can use wavesurfer with Angular [without typings](https://stackoverflow.com/a/27434010/5097199).

**Comment by logavdm** [comment]
Thanks for the reply guys.
