### ISSUE TITLE
Stereo Mp3 files don't work on Safari 11

### ISSUE THREAD

**Issue by websolab** [katspaugh/wavesurfer.js#1562]
### Wavesurfer.js version(s):

wavesurfer.js 2.1.3 (2019-01-21)

### Browser version(s):
Safari 11.1.2 (11605.3.8.1)

### Code needed to reproduce the issue:

I took the code from the original site https://wavesurfer-js.org
The fact is that the code is works with .wav files in all browsers. 
But .mp3 doesn't work in Safari.
You can check everything here.

https://laravel57.websolab.com/

Thanks a lot for help!

**Comment by thijstriemstra** [comment]
See https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility.

There's this though: https://github.com/katspaugh/wavesurfer.js/blob/master/src/webaudio.js#L405

Can you comment that out and see if that makes a difference?

**Comment by ronhornbaker** [comment]
> See https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility.
> 
> There's this though: https://github.com/katspaugh/wavesurfer.js/blob/master/src/webaudio.js#L405
> 
> Can you comment that out and see if that makes a difference?

I tried commenting out lines 412-415 (assuming that was the snippet to which you were referring), and it didn't help. In fact, Safari wouldn't load either a wav or mp3 at all.

I'm seeing this mp3 wave rendering bug with Safari on Mac and iOS, too: mp3 results in no waveform being generated, while wav of same content works fine. My only workaround is to use only WAV files, which is unfortunate due to their size. Not sure it has anything to do with stereo, but the mp3 file I'm currently testing is in stereo.

**Comment by thijstriemstra** [comment]
@ronhornbaker that code creates a single channel buffer, can you try and change it to 2 channels, e.g.

```
const newBuffer = this.createBuffer(2, 4096, this.sampleRate);
```

and adjust the buffer size if necessary.

**Comment by websolab** [comment]
The problem was in mp3 files. Something with render options. I tried different mp3 files downloaded from network and it's works now.
