### ISSUE TITLE
png instead of JSON

### ISSUE THREAD

**Issue by diegoiglesias** [katspaugh/wavesurfer.js#1757]
Is it possible to use png images instead of JSON data to render waveforms?

I'm having problems rendering large JSON strings on the browser, so I guess it'll be more convenient to place images and avoid the issues.

Thanks

**Comment by aburai** [comment]
sounds not easy, but possible
i do not know an existing solution for this, so i think you must do it on your own

let us come back to your problem with rendering large JSON strings,
what exactly is the problem?
i think, if we search for a solution, then how to handle large sets of peaks,
if the current solution is not good enough

**Comment by entonbiba** [comment]
@diegoiglesias if you need to generate a waveform png from an audio file you can do it here https://waveform.al. However you still need to load the audio data itself to play something, that will still take time if it's a large json object. Do you have the json payload in question that is causing issues?

You can also try setting the backend to MediaElement to load it as html5 audio instead of webaudio. https://wavesurfer-js.org/example/audio-element/index.html

**Comment by entonbiba** [comment]
there's also the option of reducing the size of the waveform peaks by doing the following:
```
var wavesurfer = WaveSurfer.create({
    container: document.querySelector('#waveform'),
    barWidth: 3,
    barHeight: 1, // the height of the wave
    barGap: 1 // the optional spacing between bars of the wave, if not provided will be calculated in legacy format
});
```

**Comment by joeytwiddle** [comment]
The FAQ generates JSON data like this:

```sh
audiowaveform -i long_clip.mp3 -o long_clip.json --pixels-per-second 20 --bits 8
```

If you change that `20` to `2`, does that reduce the size of your JSON files by 90%?
