### ISSUE TITLE
How to continue dragging a wavesurfer region even outside canvas area?

### ISSUE THREAD

**Issue by adityakrshnn** [katspaugh/wavesurfer.js#2006]
I wanted to know if there is any way to continue dragging/resizing a region even outside the wavesurfer.js canvas area. Attaching video.

![qWaKi](https://user-images.githubusercontent.com/23035769/87704670-60cb4480-c7ba-11ea-9230-db9a27e33eb8.gif)

**Comment by sundayz** [comment]
The code that handles region dragging needs some improvements, I'm actually going to start working on a PR that fixes this soon, because I noticed this problem too.

If you really needed to fix it urgently you could probably add your own click event listeners and set the region size yourself manually when the mouse is moved.

**Comment by adityakrshnn** [comment]
Can I make a pull request for this issue? I was able to solve it

**Comment by sundayz** [comment]
Of course

**Comment by adityakrshnn** [comment]
Great! Can you give me access to push? I have made a new branch.

**Comment by sundayz** [comment]
I can’t, I’m just a user. I think if you make a fork, do the changes there and submit a PR it’s fine
