### ISSUE TITLE
I want to use 2-channel waveform and save the JSON data generated by waveform; however, after using the exportpcm method, the result can only be empty

### ISSUE THREAD

**Issue by guisha** [katspaugh/wavesurfer.js#2152]
var wavesurfer = WaveSurfer.create({
			container: '#waveform',
			progressColor: 'red',
			waveColor: "#666666",
			height: 65,
			fillParent:true,
			forceDecode:true,
			partialRender:true,
			pixelRatio:1,
			splitChannels: true,
			barWidth: 0,
			
		
		});
		 wavesurfer.load("music/work.mp3"); 
		wavesurfer.on("ready", function() {
			
			console.log(wavesurfer.exportPCM('1024','10000',true,0));
		})
       result：
         Promise {<resolved>: "[null,null,null,null,null,null]"}；
       How to solve this problem！

**Comment by aburai** [comment]
1. use backend: 'MediaElement' in your params
2. listen to 'waveform-ready' instead of 'ready'
3. exportPCM() does not work with splitted channels, but you can use wavesurfer.backend.getPeaks(1024) to get the peaks
4. manually map the peaks and round to accuracy you need

hope that helps, i do not use this way, i have just a quick look in the sources

this is what wavesurfer do and the [].map.call() with splitted peaks like [Array(2048), Array(2048)] breaks the pcm data
```
const peaks = this.backend.getPeaks(length, start);
const arr = [].map.call(
            peaks,
            val => Math.round(val * accuracy) / accuracy
        );
```

**Comment by guisha** [comment]
const arr = [].map.call(
            peaks,
            val => Math.round(val * accuracy) / accuracy
        );
Thank you for your reply, this method can only traverse one, not multiple, I have 2 channels
