### ISSUE TITLE
Unable to play large m4a audio file using wavesurfer

### ISSUE THREAD

**Issue by lichangwei123** [katspaugh/wavesurfer.js#2799]
Unable to play large m4a audio file using wavesurfer

**Comment by katspaugh** [comment]
Since wavesurfer decodes the file in the browser and puts them into a JavaScript array, large files may fail to decode due to memory constrains.
We recommend using pre-decoded peaks for large files.
See this example: https://wavesurfer-js.org/examples/#predecoded.js

You can use a tool like https://github.com/bbc/audiowaveform to generate peaks.

**Comment by lichangwei123** [comment]
It's not the file size .Unable to play m4a audio file.What should I do

**Comment by lichangwei123** [comment]
> 

It's not the file size .Unable to play m4a audio file.What should I do

**Comment by lichangwei123** [comment]
It could be the electron environment

**Comment by katspaugh** [comment]
Any other piece of information you might want to share?

**Comment by katspaugh** [comment]
I’ll close this since different browsers support or don’t support certain file formats and there’s little we can do about it.
