### ISSUE TITLE
If loadBlob() is suddenly undefined for you, look here.  It has been removed and here is the fix.

### ISSUE THREAD

**Issue by roschler** [katspaugh/wavesurfer.js#3059]
My project used the `loadBlob()` method for many months without error.  A few days ago it "disappeared".  Suddenly I started getting a "loadBlob is undefined" error from Chrome DevTools.  I have no idea how this happened and can only surmise that somehow I or WebStorm did an unintended package update since that method has been removed.  I lost about 2 hours frantically switching between many branches and rerunning my app with the result always being that `loadBlob` was `undefined`.

To make sure that I had not lost my mind and for others here that might now be aware of this method, you can see it being described in these Stack Overflow posts:

Fortunately I stumbled on to this bit of code that explains how to use the `load` method directly with a blob:

https://github.com/search?q=repo%3Akatspaugh%2Fwavesurfer.js%20loadBlob&type=code

Here is the code in case the link dies:

FILE: src/plugins.record.ts
```js
private loadBlob(data: Blob[], type: string) {

const blob = new Blob(data, { type })
this.recordedUrl = URL.createObjectURL(blob)
this.restoreInteraction()
```

FILE: README.md

* `loadBlob` – use `URL.createObjectURL()` to convert a blob to a URL and call `load(url)` instead

To the developers: This is a **fantastic** package.  I know that most developers are pretty manic about removing unnecessary code, but in the future could you consider having the deprecated methods throw an exception instead of flat out removing them?  That would save some users of your library like myself substantial pain.  

Yes, the removal was definitely properly documented in the README, but when you have a giant code base and suddenly a piece of code that worked fine for months stops working, your first instinct is to scan your old code/branches to see where you broke something, rather than looking for a package that may have remove a method.  Especially in a case like mine where I did _not_ do an explicit package update.  I still don't now how the update took place without my explicit action.  

Either way, again, many thanks for this brilliant package.

**Comment by katspaugh** [comment]
Hey @roschler, thanks for writing this up!

It was a major version upgrade (v6 -> v7) which introduced not just this but multiple breaking API changes intentionally. Automatic upgrades like this typically shouldn’t happen, unless your package.json explicitly allows that. Namely, it would have to say `”wavesurfer.js”: “*”`, meaning always download the latest major version. Or, if you’re using a public CDN, the script tag probably doesn’t include a version (which is unfortunately what we used to recommend in the readme for a while, but not anymore).

That said, I acknowledge the update could’ve gone smoother. Good idea about throwing a deprecation message next time.

I might restore this method since there’s been other people asking about it.

Apologies for the trouble and thank you for informing others about how to fix this.

**Comment by roschler** [comment]
@katspaugh Thanks!
