### ISSUE TITLE
Error in timeline when using container param

### ISSUE THREAD

**Issue by pokemon963** [katspaugh/wavesurfer.js#3070]
When I do:
```
wavesurfer = WaveSurfer.create({
          container: '#waveform',
          autoScroll: true,
          height: 80,
          // barWidth: 2,
          // barHeight: 1, // the height of the wave
          // barGap: null, // the optional spacing between bars of the wave, if not provided will be calculated in legacy format.
          waveColor: 'violet',
          progressColor: 'purple',
          normalize: true,
          plugins: [
            WaveSurfer.Timeline.create({
                container: '#timeline'
            }),
          ]
      });
```

I get an error due to there not being an appendChild in the timeline plugin

**Comment by katspaugh** [comment]
The container param in the Timeline options expects an HTML element, not a selector. See https://wavesurfer-js.org/docs/types/plugins_timeline.TimelinePluginOptions

I can see that it's confusing, since it's different than the container param in the wavesurfer options. So I'll make it accept a selector too. It's not a bug, though.
