### ISSUE TITLE
Seeking doesn't work if no audio is provided

### ISSUE THREAD

**Issue by jagthedrummer** [katspaugh/wavesurfer.js#3298]
## Bug description

I'm using wavesurfer.js to render a waveform without audio, which is working great.

When I call `setTime` to try to move the cursor to a particular point it always stays at 0:0. If I register for the `interaction` event it's picking up clicks at the right spot, but the cursor never moves.

## Environment

 - Browser: Chrome

## Minimal code snippet

```javascript
wavesurfer = WaveSurfer.create({
  container: '#some-container',
  interact: true,
  dragToSeek: true,
  peaks: [/* valid peak data goes here */],
  duration: 300
});
wavesurfer.setTime(150);
```

## Expected result

I'd expect the cursor to move to the halfway point.

## Obtained result

The cursor stays at the beginning.

## Screenshots

When passing in a `url` subsequent calls to `setTime` will move the cursor:

![CleanShot 2023-10-25 at 14 40 43](https://github.com/katspaugh/wavesurfer.js/assets/58702/9261ecd8-aa9b-44a4-b18d-767a853713f9)

When a `url` is not passed in calls to `setTime` do not move the cursor:

![CleanShot 2023-10-25 at 14 40 00](https://github.com/katspaugh/wavesurfer.js/assets/58702/a099aa29-06f5-4a09-a174-0c56679f19df)

**Comment by mvynhb** [comment]
Hi @katspaugh 

I understand that seeking is not possible if the audio is not loaded, however this also happens with this scenario:

```js
media = new Audio(src)
media.preload = 'none'
  this.surfer = WaveSurfer.create({
      container: wave,
      media: media,
      peaks: peaks,
      duration: duration
  })
```

So I do pass a media element, however I set preload to none. In this case I am not able to seek. I do not want to load metadata because I already have peaks and duration. Is there a way to still move the cursor and seek even when no metadata is loaded?

I understand the workaround, but in my case I do want the audio to play when play button is clicked.

**Comment by katspaugh** [comment]
I don't think it's possible with an actual audio element.

You should either use the Web Audio option as per the workaround above, or you have to subscribe to one of the events indicating the audio has loaded, like `loadedmetadata` or `canplay`.

**Comment by bernardwiesner** [comment]
@katspaugh 

Thanks for the quick reply!

Actually what I want to do is simply allow the user to move the cursor through the player/waveform without playing, and when they decide to play they press the play button.

The same as here: https://wavesurfer.xyz/examples/?webaudio.js, just without fetching any metadata, setting the preload to `none`. The reason is because I have a long list of episodes +30, and I dont want to drain user's bandwidth every time the load the page.

Currently my workardound is to have a click event on the waveform with the following method:

```js
playAndPause () {
    if (this.media.preload === 'none') {
        this.play()
        this.pause()
    }
},
```

It's not ideal, since it starts downloading the whole audio when the user clicks on the waveform. Do you know if there is a better way to just download metadata when the user clicks on the waveform, so they can move the cursor?

**Comment by mvynhb** [comment]
@katspaugh 

Thanks for the quick reply!

Actually what I want to do is simply allow the user to move the cursor through the player/waveform without playing, and when they decide to play they press the play button.

The same as here: https://wavesurfer.xyz/examples/?webaudio.js, just without fetching any metadata, setting the preload to `none`. The reason is because I have a long list of episodes +30, and I dont want to drain user's bandwidth every time the load the page.

Currently my workardound is to have a click event on the waveform with the following method:

```js
playAndPause () {
    if (this.media.preload === 'none') {
        this.play()
        this.pause()
    }
},
```

It's not ideal, since it starts downloading the whole audio when the user clicks on the waveform. Do you know if there is a better way to just download metadata when the user clicks on the waveform, so they can move the cursor?

**Comment by katspaugh** [comment]
I haven’t tested this but you can probably dynamically set preload to metadata on click and call the load method on the audio element. https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/load

**Comment by katspaugh** [comment]
I’ll reopen this issue to see if we can just visually set the cursor on click and schedule an actual seek action for when metadata is loaded.

**Comment by katspaugh** [comment]
Hey all, I've released this feature in 7.7.0. Please let me know if it works for you!

**Comment by jagthedrummer** [comment]
Hey @katspaugh, I just updated to 7.7.0 and this is working great. Thank you!

**Comment by uholland** [comment]
Hey @katspaugh, can you please update wavesurfer/react to the new dependency please? :-) This would be awesome. Thank you!
