### ISSUE TITLE
Waveform not drawing with media option?

### ISSUE THREAD

**Issue by maxiedaniels** [katspaugh/wavesurfer.js#3425]
I'm using wavesurfer 7.5.2 and testing in Chrome and Safari, and last night I realized the audio wasn't loading in Safari when using a normal setup (load() function in wavesurfer). I was getting an error about unhandled promise/unsupported. After testing a lot, it seemed it was due to some protection in Safari, and there was a bug report here where the suggest was to use Audio() and pass that to wavesurfer's media option.
That fixed the issue with the audio not playing in safari, but now there's no waveform loading, probably because i'm not using load() anymore. Any advice??

**Comment by katspaugh** [comment]
What was the error exactly, can you screenshot it in the console? Also please share the audio file.

**Comment by initred** [comment]
I'm also experiencing this problem.

I am experiencing an issue when using video.js in combination with wavesurfer's media options.
The library does not render, and the 'ready' event does not fire on iOS devices.
I cannot find any errors in the console.
The video format I'm using is mp4/h264.
This issue is observable both on the iOS simulator and actual iOS devices.

Thank you for maintaining that library. Respectful.

**Comment by katspaugh** [comment]
If it plays the audio in an external media element but fails to decode and render it, it can mean two things:
* The file cannot be fetched due to CORS
* The audio failed to decode because its format isn’t supported by Web Audio

You can see which of these two your issue is by checking for errors in the console. If it’s CORS, you can fix it by hosting the audio file on a CORS-enabled server. If it’s the decoding, you can pre-decode the audio (e.g. on the server) and pass peaks to wavesurfer.
