### ISSUE TITLE
Draggable region covered by undraggable region

### ISSUE THREAD

**Issue by shirshendu** [katspaugh/wavesurfer.js#366]
Thanks for your amazing work with wavesurfer!

When a small, draggable region is covered completely by a larger, undraggable region, I am unable to drag the smaller region.
This 'covering' happens when the larger region is created *after* the smaller region. If the smaller one is created second, then everything works fine.
![image](https://cloud.githubusercontent.com/assets/1880361/6365700/0aefcee8-bce2-11e4-931a-2a1072e43149.png)
-- The small black regions are supposed to be draggable, but are not accessible because the pink region was created after them, as undraggable.

Is this behaviour intentional?
Also, I am unable to find which object/variables controls this sequencing in the backend so that I can adjust it according to my purpose. Could you please help?

**Comment by katspaugh** [comment]
Regions are made of your usual DOM element, so this is the expected behaviour.

> Also, I am unable to find which object/variables controls this sequencing in the backend so that I can adjust it according to my purpose.

The sequencing is chronological, so you control it by adding the top regions last. If you need to reorder the layering, there's currently no API for that. However, you can delete a background layer and create a new one with the same properties–it will go on top.
