### ISSUE TITLE
Is there support for buffering?

### ISSUE THREAD

**Issue by chalmagean** [katspaugh/wavesurfer.js#369]
First of all, thanks for this awesome library.

I'm trying to figure out if audio buffering is supported. An use case would be that the user can hit play before the whole file was loaded (kinda like what YouTube does with videos).

If there is and I've missed it, can you please send a link with the example?

**Comment by katspaugh** [comment]
Hi Cezar,

Thanks for your interest!

Buffering is supported with the `MediaElement` backend. Here is the link: http://www.wavesurfer.fm/example/audio-element/

Only the audio is buffered, not the image. In order to generate a waveform, the whole audio file needs to be downloaded (while it is also loaded into a buffered audio element).

**Comment by chalmagean** [comment]
So you'll be able to hit play even if the file didn't completely load yet (sorry but it's not obvious form the example page)?

**Comment by katspaugh** [comment]
Yes.

**Comment by chalmagean** [comment]
Awesome, thank you @katspaugh
