### ISSUE TITLE
WaveSurfer Not Displaying Waves When Loading Audio from AWS S3

### ISSUE THREAD

**Issue by waelantar** [katspaugh/wavesurfer.js#3957]
**Description:**
I encountered an issue while attempting to load audio from an AWS S3 URL using WaveSurfer. The audio plays correctly, and I can hear the sound, but the waveform does not appear. However, when using a local file, the waveform displays as expected. This happens for both .wav and .mp3 formats. Below is the code snippet I am using:

typescript
```
private initializeWaveSurfer() {
    setTimeout(() => {
        this.waveSurfer = WaveSurfer.create({
            container: this.container.nativeElement,
            waveColor: '#EBE3E1',
            progressColor: '#D22C19',
            fetchParams: {
                mode: 'no-cors',
                method: 'GET',
                credentials: 'same-origin',
                headers: {
                    'cache-control': 'no-cache',
                    pragma: 'no-cache'
                }
            }
        });
        this.waveSurfer.on('audioprocess', (e: number) => {
            this.currentTime = e;
        });
        this.waveSurfer?.load("s3Url"); 
    }, 0);
}
```
Steps to Reproduce:

Configure WaveSurfer with the above settings.
Load an audio file from an AWS S3 URL.
Observe that the audio plays, but no waveform is displayed.
Replace the AWS S3 URL with a local file path and observe that the waveform appears correctly.
Expected Behavior:
The waveform should be displayed when loading audio from an AWS S3 URL, similar to how it appears when using a local file.

Observed Behavior:
The audio plays, but the waveform does not appear for files loaded from AWS S3.

Additional Information:

This issue occurs for both .wav and .mp3 files.
I suspect it might be related to CORS or how WaveSurfer handles remote file loading.
Environment:

WaveSurfer version: ^7.8.9
Browser: Chrome and edge
Operating System: Windows 11
Would appreciate guidance on how to resolve this issue.

**Comment by katspaugh** [comment]
Please use the search function in this forum and in the issues, this was asked and answered multiple times.

**Comment by waelantar** [comment]
I have searched already and I didn't find a solution for my case

**Comment by katspaugh** [comment]
https://github.com/katspaugh/wavesurfer.js/issues/3510#issuecomment-2491875464

**Comment by waelantar** [comment]
@katspaugh I tried to use azure too but it's the same problem and tried different browsers removed extenstion use private window no luck do you have any suggestion to the cause of the problem why it cannot be decoded

**Comment by LouMM** [comment]
I have the same issue. I am using React.js server-side rendering for mine. I see the audio file retrieved, and I can play the audio just fine, but the waveform and the progress are not rendering as the color defined for them.

![Waveplayer](https://github.com/user-attachments/assets/1a994611-f370-42fa-9e94-9b0d4f8e7bab)

**Comment by waelantar** [comment]
@LouMM  can you please share with me the solution if you find one and thank you

**Comment by teito-dev** [comment]
@waelantar @LouMM  the issue is happening because you're using no-cors param in your audio loading 

The problem with 'no-cors' mode when using wavesurfer or even vanilla fetch to get the audio is you're attesting to the user's browser that it can bypass CORS security measures, since you pinky promise to never run Javascript on the audiofile data loaded from 3rd party cross origin site from your own website/localhost in your browser (the third party side you're loading the audio from is in this case aws s3 or cloudfront depending on setup)

Thus since you use no-cors you are promising to not use javascript in browser on that audio, so while you can play the audio file, the waveform doesnt get rendered, the .getTotalDuration like functions that need js to process the audio file, do not work in no-cors mode.

Thus you must change the AWS S3 CORS config to make it work 

You must use cors mode in wavesurfer thus, 
My working config looks something like this : 
```javascript
const wavesurfer = WaveSurfer.create({
        container: waveformRef.current,
        waveColor: '#27272A',
        progressColor: '#8A8A8A',
        cursorColor: 'transparent',
        barWidth: 2,
        barGap: 1,
        barRadius: 2,
        height: 48,
        url: audioUrl,
        fetchParams: {
          mode: 'cors',
          credentials: 'omit',
          headers: {
            'Accept': 'audio/mpeg, audio/mp3, audio/*;q=0.8, */*;q=0.5',
          }
        }
      });
```

It loads the audio file just fine from cloudfront (via aws s3) you can load from aws s3 directly too the same way 

<img width="334" height="162" alt="Image" src="https://github.com/user-attachments/assets/d74a93e5-7bcf-4ba2-ab33-59ee1500da59" />

and the waveform does render properly 

So under aws s3 , open your bucket's console, then go to the permissions tab  then scroll down to Cross Origin resource sharing (CORS) input box

enter something like this 
```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "PUT",
            "POST"
        ],
        "AllowedOrigins": [
            "https://<your website host>"
        ],
        "ExposeHeaders": []
    },
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "PUT",
            "POST"
        ],
        "AllowedOrigins": [
            "http://localhost:3000"
        ],
        "ExposeHeaders": []
    }
]
```

Make sure you have the GET in the allowed methods always, and if you want it simpler then you can just have 
```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "PUT",
            "POST"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]
```

I personally dont use an all-encompassing * to allow all origins to make sure only my own website and local dev env can load assets or send requests personally,  just make sure GET is in allowed methods, that's all

And voila now you can make it work in cors mode, change from no-cors to cors and it should work just fine.

I hope this is helpful for anyone else after this who faces the same issue.
