### ISSUE TITLE
Specifying the width of the waveform pieces and allowing for spacing between them

### ISSUE THREAD

**Issue by JoshSmith** [katspaugh/wavesurfer.js#416]
Here's a visualization of the effect I'm trying to achieve.

![screen shot 2015-03-24 at 5 12 03 pm](https://cloud.githubusercontent.com/assets/321667/6815901/2b8fbb1e-d249-11e4-9ff4-53a37a2993d7.png)

I thought, mistakenly, that `minPxPerSec` would have done this. Is this possible? I'd be happy to help implement if not.

**Comment by JoshSmith** [comment]
This actually looks close to a duplicate of https://github.com/katspaugh/wavesurfer.js/issues/242

**Comment by katspaugh** [comment]
To achieve this you'd need to change the way `drawWave` draws the waveform.

Currently it draws a single huge filled path. This allows drawing nicer waveforms with less peaks data, because it runs smoothly from peak to peak. We'd like to keep this behavior as default.

To do what you want, you'll have to draw each peak as a separate rectangle (`drawRect`), with appropriate spacing between them. Please also make sure the rectangles and gaps look nice on different "zoom levels", i.e. with different `minPxPerSec` values.

So yeah, go ahead and make a pull request, I'll help working on this as much as I can.

**Comment by katspaugh** [comment]
Implemented as the `barWidth` parameter.
