### ISSUE TITLE
ELAN plugin doesn't use mediaelement backend for long audio files?

### ISSUE THREAD

**Issue by stephenlaughton** [katspaugh/wavesurfer.js#428]
I was just wondering if this is on purpose as the WebAudio documentation recommends using createMediaSourceElement with audio files longer than 1 minute.

**Comment by katspaugh** [comment]
Our media-element backend and Web Audio's media-element source are two different things. Our media-element backend is just a regular HTML `<audio>` element, it is used only to play the audio.

To display the waveform, you need to download and decode *the whole* audio file (using Ajax request). And that's the main problem with long files–the decoder fails due to memory limits.

Alternatively, you can pre-render waveform data on the server and pass it as an array to wavesurfer.js, so that it plays using the `<audio>` element and draws the waveform using this array.

For further details, please look at the code of this page: http://www.wavesurfer.fm/example/audio-element/
