### ISSUE TITLE
Ready event not triggered at the right time

### ISSUE THREAD

**Issue by pkeuter** [katspaugh/wavesurfer.js#429]
First off: what a nice tool this is. 

I do have a little problem with events though. It looks like the ready event not triggers like it says on the site:  "When audio is loaded, decoded and the waveform drawn." It triggers after I start play playback. Maybe I'm doing something wrong here, could be. I'm using it inside of AngularJS

**Comment by thijstriemstra** [comment]
Can you reproduce it with the AngularJS example?

**Comment by katspaugh** [comment]
@pkeuter the example Thijs is referring to is this: https://github.com/katspaugh/wavesurfer.js/blob/master/example/angular/app.js

Make sure your AngularJS directive isn't turned off with `ng-if` until you press the play button.

**Comment by pkeuter** [comment]
I can reproduce it with the example. http://plnkr.co/edit/LRKeAglgUxwHBLzW1veN?p=preview

As you can see, the text only dissapears when you press play.

**Comment by liamdv4** [comment]
I'm using MediaElement mode (without autoplay) and loading an hour-long MP3 which takes a little while. The event fires for me as soon as the player instantiates (before I press play). Again this is not quite how the event is described because it takes 10-15s before the waveform is drawn.

I was hoping to be able to implement a spinner or "Generating waveform..." message during that time which I could remove when the "ready" event fired.

**Comment by katspaugh** [comment]
@liamdv4 thanks, looks like a bug.

**Comment by liamdv4** [comment]
I think it would be ideal to leave the ready event as it is (since the player is, indeed, ready to play at that point), but add a new event for when the waveform has been drawn. Thanks.

**Comment by katspaugh** [comment]
Yes, makes sense.

**Comment by hungryforcodes** [comment]
+1 for new event. I had this problem with "ready" as well, but have since used it to know when the player is ready as suggested.

**Comment by chinshr** [comment]
@pkeuter check if this #565 works for you?

**Comment by katspaugh** [comment]
Solved in ##856.
