### ISSUE TITLE
Dragging a region doesn't work outside of scrollbar

### ISSUE THREAD

**Issue by pkeuter** [katspaugh/wavesurfer.js#430]
When I try to drag a region, with a part of that region inside view and a part outside of the view, I expect that the scrollbar moves with my mouse so I can select more that what's currently in view. Maybe the current behavior (selecting only inside view) is the expected behavior for others?

**Comment by katspaugh** [comment]
I agree that scrolling the waveform so that the dragged regions stays in the viewport is the desired behavior. Let's call it a bug.

**Comment by maxehnert** [comment]
I haven't had a chance to check this with a mouse yet, but on my laptop if I click and hold over the region I can use the trackpad to drag the region around including outside of the viewport. The viewport will scroll with the region across the file. Also click and hold on a region and using arrows also works for dragging the region outside the viewport. 
But I agree though that this is more work than what is intuitively expected.

**Comment by GitHubRakeshSharma** [comment]
Has there been any kind of conclusion. I currently face the same problem

**Comment by roboswank** [comment]
@GitHubRakeshSharma 
I am working on a solution.
The real issue comes into dealing with situations where the left or right bounds of the container are at the edge of the document. You cannot get mouse events when the mouse is not within the browser (for obvious reasons). So two approaches have to be made. The first for when it is not up against the edge of the document (easy) - just have to calculate the distance the mouse has gone beyond the container and adjust the scrolling speed in that direction until the mouse re-enters the bounds.
The second (harder, as in there are quite a few ways to deal with this and none of them are going to be able to please everyone) is catching the `mouseleave` event on the document (while resizing/dragging) and then throttling a scroll in the appropriate direction until the mouse reenters the document or the min/max scroll has been met (whichever comes first).
I have it functioning but it needs some polishing before I submit a PR. I expect to have it done before the weekend is up... just all depending on my workload at the office.

**Comment by GitHubRakeshSharma** [comment]
@roboswank I am deeplay thankful... I really wasn't able to figure that one out. I does work more or less. Still does not fix the scrolling problem while dragselecting a region but I guess I can work that one out based on your solution!!

**Comment by anteph** [comment]
Hi! 

Thank you very much for the fix :)

I've been testing the drag / resize of a region near the edges and it seems to be working fine for the left side but, for some reason, it is not working when dragging / resizing for the right side.

Sometimes, if I drag to the left margin and, while sustaining the drag, move the cursor to the right edge, then it works (not deterministic).

This happens in chrome, edge and firefox.

Is it a known problem or might it be related with my configurations?

Not sure if this affects, but I'm using React.

Thanks for the attention  :)
Nuno Santos

**Comment by harryradford** [comment]
These region options for scrolling the waveform when dragging the region are not available anymore. @katspaugh is it possible for these options to be added again?

**Comment by katspaugh** [comment]
@harryradford thanks for flagging this, I've made an issue to bring them back: https://github.com/katspaugh/wavesurfer.js/issues/3244
