### ISSUE TITLE
Large waveform disappears on load/when zooming

### ISSUE THREAD

**Issue by chrislatina** [katspaugh/wavesurfer.js#458]
I've extended to angular example to include drag/drop + zooming. When I load a large file (I've been using this wav https://archive.org/details/Allen_Ginsberg__Anne_Waldman__Steven_Tay_92P016), draw fails. It works for smaller files without a problem.

If you load this large file for example via angular, chrome will crash. Dragging and dropping however works! Zoom works for a little bit, but then the waveform disappears. It does still play though.

**Comment by chrislatina** [comment]
Looks like there's a maximum size for the canvas: http://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element

Things begin to slow when computing: this.getDuration() * this.params.minPxPerSec * this.params.pixelRatio

Maybe bracketing longer audio files into chunks that fit on the canvas and swapping them out will help

**Comment by katspaugh** [comment]
Yes, probably we should have the limit set in the drawing code, too. And throw an error if exceeded.

**Comment by maxehnert** [comment]
I've come across this myself but haven't fixed it, just did workarounds. However some people have built tools for cutting and splicing canvas elements. This is something that could be done in the background to create a seamless work flow. Check out this issue https://github.com/katspaugh/wavesurfer.js/issues/419. Additionally this repo https://github.com/ffdead/wav.js can be used for cutting wav files into smaller pieces which could then be loaded like a playlist. So there are a few different approaches to solving this issue. For now, I just use short audio files because I need to zoom in to a millisecond scale. 
Loading a long audio file however even if you do get it to render has serious memory consumption problems (at least in Chrome). I was often seeing over 1gb useage to render a 30 minute audio file and less than 100 minPxPerSec. Any more zoom and it would disappear as you mentioned, but still play the audio.

**Comment by redtopia** [comment]
I'm having the same problem with large audio files. It happens anytime after the file loads. What would be the workaround for a large file in terms of drawing and memory consumption? I was hoping to use this for all audio files, and there could be several on a page. Is this impractical?

**Comment by katspaugh** [comment]
@redtopia the workaround would be to make the canvas smaller:

 * Reduce height
 * Reduce `minPxPerSec`
 * Set `pixelRatio` to 1

**Comment by chinshr** [comment]
I am running into similar issues with large audio files and I like the playlist idea that @maxehnert mentions.
