### ISSUE TITLE
Grouping regions

### ISSUE THREAD

**Issue by berio** [katspaugh/wavesurfer.js#463]
Hi, 
first of all, congrats for you guys, wavesurfer.js is awesome.
I am using it in a project where I have to use 2 different kind of regions. Let's say for instance that I need a group of regions for user audio comments and another one for automatic audio transcript. Is there a way to create different kind of region and group them?
If not, could you give me a first starting point to implement it?
Thank you so much

**Comment by maxehnert** [comment]
I'm not sure if this will cover your situation, but for me, I needed to make regions, and also have small markers similar to the regions. I could not use the same regions plugin for both because they needed different functionality. What I did was modify the regions plugin and rename it for my markers. So now I have a regions plugin and a separate marker plugin. 
My suggestion would be to add a second regions plugin and modify and rename it to work with the additional use you require. 
I'm not sure what you mean by group them however. Could you clarify this?

**Comment by katspaugh** [comment]
@berio you can add arbitrary data to your regions and filter/group them according to this data.
Here's an example adapted from [here](https://github.com/katspaugh/wavesurfer.js/blob/master/example/annotation/app.js#L230):

```
         wavesurfer.addRegion({
            start: 10,
            end: 20,
            data: {
                group: 'user comments'
            }
        }); 
```

Group like this:
```
        var userCommentRegions = [];

        Object.keys(wavesurfer.regions.list).forEach(function (id) {
            var region = wavesurfer.regions.list[id];

            if (region.data.group == 'user comments') {
                userCommentRegions.push(region);
            }
        });
```

**Comment by berio** [comment]
Thank both of you for your answers. I did what maxehnert says and it is working perfect. I know, katspaugh, that your approach is more clean, it would be good give it a try in the future.
Again, congrats for wavesurfer.js, the more I work with it, the more I like it.

**Comment by katspaugh** [comment]
:thumbsup:

**Comment by maxehnert** [comment]
@katspaugh that is a great suggestion. I'm not sure yet if I'd be able to change mine to something like that, but I'm going to look into it and try it out.  +1 for simplicity!

**Comment by katspaugh** [comment]
@maxehnert I think your solution is fine as well, as long as your markers differ greatly from regions.
