### ISSUE TITLE
Use WebAudio with prerender peaks ?

### ISSUE THREAD

**Issue by walane** [katspaugh/wavesurfer.js#465]
Hi,

Can we use WebAudio with prerender peaks ? Is it technically possible ?
I see that partial content is available on media element, is it available with WebAudio too ?

Thank you :)

**Comment by katspaugh** [comment]
Hi,

It's possible but it's not in the code.

As for the second question, we use Web Audio's buffer source which requires the whole file downloaded, so no, no partial content. If we used media element source instead of buffer source, it would behave similarly to regular media element, but we don't use it.

**Comment by walane** [comment]
Ok thank you for your answer !

I have to use a flash solution because MediaElement has no any precision when seeking :/

**Comment by kavishatalsania** [comment]
@katspaugh How can we prerender peaks with WebAudio?

Please Help me!
