### ISSUE TITLE
AudioElement rendering issue with 10.0.30

### ISSUE THREAD

**Issue by DCDJ** [katspaugh/wavesurfer.js#491]
Is this waveform rendering issue a known bug with wavesurfer 10.0.30?

I have my server generate all the waveforms and feed the JSON data into WaveSurfer, all was working before I upgraded recently to 10.0.30

![screenshot from 2015-07-29 14 20 25](https://cloud.githubusercontent.com/assets/3400414/8958525/3f6a6d9c-35fd-11e5-9526-39082e68e06a.png)

JSON data if required: http://pastebin.com/VUv2NcR7

Here is my setup:

````javascript
that.wave.init({
            container: '#waveform',
            //    waveColor: /* that.getRandomColour(), */ "#33EEAA",
            //    progressColor: /* that.getRandomColour(), */ "#FF2266",
            waveColor: /* that.getRandomColour(), */ "#00BFFF",
            progressColor: /* that.getRandomColour(), */ "#FF00FF",
            dragSelection: false,
            backend: 'AudioElement',
            hideScrollbar: true,
            cursorWidth: 2,
            //normalize: true
        });
````

Works perfectly if I comment out the backend tag..

**Comment by katspaugh** [comment]
I think it might have to do with changes from #478. @dpwe can you take a look?

**Comment by katspaugh** [comment]
I suggest you should use 1.0.29 while we fix it.

**Comment by DCDJ** [comment]
Thanks @katspaugh !

**Comment by dpwe** [comment]
@DCDJ : #478 changed the intermediate format for waveform display from a sequence of nonnegative peak values to a sequence of *pairs* of nonnegative peaks, nonpositive peaks (i.e., max(block of samples), min(block of samples)).  So the length of these vectors doubled.  The nice part about this is that the displayed waveforms can now be asymmetric and more "realistic".

I don't have a good insight into where these vectors are used, but it sounds like you were generating your  own.  Would you be able to modify the vectors you generate to feed (max,min) pairs instead of max(abs) sequences?

**Comment by DCDJ** [comment]
@dpwe Cheers, yes I can do that, I'll give it a go and report back here.

**Comment by thijstriemstra** [comment]
Maybe we should introduce a changelog somewhere to make it easier to upgrade.

**Comment by thijstriemstra** [comment]
@DCDJ Any news?

**Comment by DCDJ** [comment]
@thijstriemstra Sorry for lack of activity - haven't had a chance to re-generate the data yet but will get on it now and report back!

**Comment by katspaugh** [comment]
This issue should be now resolved as we support both types of pre-generated data (with negative peaks and without).
