### ISSUE TITLE
Use case: Display 24 hours worth of audio from 2 or more sources

### ISSUE THREAD

**Issue by Joshfindit** [katspaugh/wavesurfer.js#512]
This is probably way out of scope, and wavesurfer may not be able to handle it, but; is it possible?
If it's possible, is it a good idea? 
And if it's not a good idea due to limitations, will wavesurfer get better overall if we work to let it be a good idea?

![timeline application mockup based on recordium](https://cloud.githubusercontent.com/assets/1937155/9535106/5141688c-4cf4-11e5-9fbb-2c554b6d3cb1.jpg)

Let's say that there is a conference with multiple microphones recording (all above-board with consent).
- Each recording can be named based on the timestamp so that they can be loaded on the timeline without hassle.
- We mute all but one at a time
- Any sources that overlap would match up. You could hear a band play from multiple angles, for example.

Does that sound doable with wavesurfer?

**Comment by katspaugh** [comment]
This case provided the original incentive to build wavesurfer.js, by the way.
Unfortunately, currently it wouldn't be possible due to the canvas size limits (see #458), unless you zoom it out very much. If we solved the canvas issue (using windowing or multiple canvases), you would still have to [pre-decode the waveform data](https://github.com/katspaugh/wavesurfer.js/blob/master/example/audio-element/main.js#L26-L28) offline (because the browser won't handle such big audio on-the-fly).

**Comment by Joshfindit** [comment]
This provided the origional incentive? That is exciting news!
On #458 I see that there was already talk of what I was going to propose; cut the audio in to smaller segements and 'lazy load' them as needed, dropping them from memory afterwards.

Personally, I'm very comfortable with precomputing (and splitting files) if there's any way this can work.

**Comment by entonbiba** [comment]
@Joshfindit #571 was implemented a while back try it out
