### ISSUE TITLE
Modifying the Reflection

### ISSUE THREAD

**Issue by sentiasa** [katspaugh/wavesurfer.js#521]
Hi,

How can I make the reflection look like the SoundCloud waveform which is the same as the top part, but the reflected part is scaled down? I asked several times on StackOverflow but noone was able to help me. 

This is how my one looks like (There is no modifications in the code. It's a complete sound wave, I just added a overlay to achieve this)
<a href="http://imgur.com/FMxEXpV"><img src="http://i.imgur.com/FMxEXpV.png" title="source: imgur.com" /></a>

And this is the one I am trying to replicate:
<a href="http://imgur.com/jgEMx1S"><img src="http://i.imgur.com/jgEMx1S.png" title="source: imgur.com" /></a>

Obviously, they did something tricky on the bottom half as the height of reflected waves are scaled down.

**Comment by katspaugh** [comment]
Firstly, you could achieve the double color by using a gradient instead of an overlay:

var ctx = document.createElement('canvas').getContext('2d');
var linGrad = ctx.createLinearGradient(0, 64, 0, 200);
linGrad.addColorStop(0.5, 'rgba(116, 116, 116, 1.000)');
linGrad.addColorStop(0.5, 'rgba(183, 183, 183, 1.000)');

```javascript
var ctx = document.createElement('canvas').getContext('2d');
var linGrad = ctx.createLinearGradient(0, 64, 0, 200);
linGrad.addColorStop(0.5, 'rgba(116, 116, 116, 1.000)');
linGrad.addColorStop(0.5, 'rgba(183, 183, 183, 1.000)');

var wavesurfer = WaveSurfer.create({
  container: '#waveform',
  waveColor: linGrad,
  barWidth: 3,
  reflection: true
});
```
See a demo here: http://plnkr.co/edit/p8RwK4MLxmcFxZJPuE12

Secondly, the sclaed bottom half can be done by either a) modifying the drawing function, or b) modifying the waveform data if you use pre-decoded data.

The drawing function is this one: https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.canvas.js#L68

**Comment by thijstriemstra** [comment]
Maybe we could add a soundcloud style example that incorporates all those tweaks. Seems like most people want to go for such a look and feel.

**Comment by sentiasa** [comment]
I am sure this would make many people happy

**Comment by katspaugh** [comment]
See #664.
