### ISSUE TITLE
IPAD and Android

### ISSUE THREAD

**Issue by front-end-developer** [katspaugh/wavesurfer.js#570]
I noticed some issues there is not sound on IPAD with the wavesurfer.js. On Android it was strange the sound became very slow, sounded like horror on android. But on IPAD there is not sound at all.

**Comment by chinshr** [comment]
I was not able to reproduce your issue on iPad 2, iPad Retina, iPad Air and iPad Air 2, however, it did work without any problems. BTW, I am using the new `wavesurfer.init({autoplay: true});` option that you will need on iOS (due to limitations). I did not try on Android.

Could you please be more specific and share the snippet of code you use in order to see how you load the audio? Thanks.
