### ISSUE TITLE
IE Support with WebAudio polyfill

### ISSUE THREAD

**Issue by justinr1234** [katspaugh/wavesurfer.js#576]
I have managed to get IE supported using the [WAAPISim WebAudio polyfill](https://github.com/g200kg/WAAPISim) for IE.

Here's what was needed:
- Small rearrangement of code in wavesurfer.js ![Code](http://i.imgur.com/f0Eu7Rc.png)
- Swap to using AudioContext instead of OfflineAudioContext in webaudio.js ![Code](http://i.imgur.com/hx27mvN.png)
- Some modifications to the WAAPISim library to fix bugs
  ![Code](http://i.imgur.com/9FPYe0g.png) ![Code](http://i.imgur.com/5xXzZLX.png)

Here's my question:
Would you be interested in merging this code and coming up with an official solution? This will work on IE9 and higher. It creates an invisible Flash SWF to handle the audio processing while using HTML5 canvas as usual to render everything.

**Comment by katspaugh** [comment]
Hey @justinr1234! Sure, that's a very nice solution! So the polyfill doesn't support offline AudioContext?

We could remove it all together and just use normal AC, but we need to check how memory consumption changes. When I last checked, with offline AC browsers took up less memory. This could have changed if browsers have fixed their bugs since then.

**Comment by justinr1234** [comment]
It appears it uses quite a bit of cpu doing pollling to get data from JavaScript into Flash (the offline vs regular AC doesn't seem to matter). The CPU usage from Flash to Javascriot can be reduced, but I'm not sure it would be a limiting factor versus having no IE at all.
