### ISSUE TITLE
Multiple HTML Initializations: Return Audio Properties

### ISSUE THREAD

**Issue by X-Raym** [katspaugh/wavesurfer.js#589]
Hi !

I'm considering using wavesurfer inside a WordPress plugins,
it would be able to replace output of WordrPress AUDIO shortcode inside content by a wavesurfer, thanks to HTML initialisation.

It was difficult, but I manage to make to player with same HTML (no different ID or classes, just like it would be rendered with WordPress shortcode).
I also hide a way to hide the default HTML audio element, and replace it by button to control play, and I manage to integrate it in WordPress: basically, it works !

The thing is I'm stuck at some point.
I would like the audio duration and audio current time to be displayed in some span, but I don't succeed to get the infos with regular audio.duration and audio.currentTime functions.

Can you please take a look at my [code](http://codepen.io/X-Raym/details/jbRawz/) ? It will really help.
The problem is just at the end of script.

Thanks for listening :)

**Comment by katspaugh** [comment]
You are trying to access `currentTime` on a jQuery object, which is basically an array. To make it work, change `audio.currentTime` to `audio[0].currentTime`.

When you have access to the actual `audio` element, you can also listen to various events such as `canplay` (when it's loaded and ready to play) and `timeupdate` (to update your current time text)–use it instead of a time-out. More info on audio events here: https://developer.mozilla.org/de/docs/Web/HTML/Element/audio

**Comment by X-Raym** [comment]
@katspaugh 
Thank you very much for the help and the doc, what exactly what I needed ! Cheers !
