### ISSUE TITLE
Microphone plugin issue in Edge browser

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#627]
When testing the microphone example in Edge 20 I get the following error on [this line](https://github.com/katspaugh/wavesurfer.js/blob/master/src/webaudio.js#L499) of webaudio.js:

```
Invalid AudioBuffer. You may not use an AudioBuffer from an 'audioprocess' event.
```

Commenting out that line seems to fix the problem:

``` diff
diff --git a/src/webaudio.js b/src/webaudio.js
index eef8f4b..0e40480 100755
--- a/src/webaudio.js
+++ b/src/webaudio.js
@@ -267,7 +267,7 @@ WaveSurfer.WebAudio = {
         this.source.stop = this.source.stop || this.source.noteOff;

         this.source.playbackRate.value = this.playbackRate;
-        this.source.buffer = this.buffer;
+        //this.source.buffer = this.buffer;
         this.source.connect(this.analyser);
     },
```

Now, why is this line there, and is it needed for any browsers, can we live without? Or should it be disabled on edge only?

**Comment by katspaugh** [comment]
AFAIU, it won't work without this line. If it does, then we can remove it, of course. It's definetly not something specific to some browsers.

**Comment by thijstriemstra** [comment]
The microphone plugin uses the `inputBuffer` from the `audioprocess` event. The [docs](https://developer.mozilla.org/en-US/docs/Web/Events/audioprocess) mention "Note the returned AudioBuffer is only valid in the scope of the onaudioprocess function". Tried making a copy of the buffer but that doesn't seem to help either.

**Comment by longsleep** [comment]
I just ran into this issue with Edge/14.14376 - WaveSurfer works just fine for me with microphone input after removing the line as mentioned by @thijstriemstra

**Comment by thijstriemstra** [comment]
@katspaugh should we make an exception for that line for edge so it works as mentioned by @longsleep and myself?

**Comment by katspaugh** [comment]
As I said earlier, if it works without this line we can remove it for all browsers. If other browsers need, then let's make an exception for Edge.

**Comment by thijstriemstra** [comment]
any thoughts on this @mspae?

**Comment by thijstriemstra** [comment]
Here's a description of a Edge demo with mic/visualizer: https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/multimedia/web-audio

**Comment by mspae** [comment]
Hm, no idea, sorry.

But reading around in the WebAudio docs: At some point we will have Audioworkers (https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API#Audio_Workers) This isn't actionable at the moment because no browsers support it yet :rofl: but audioprocess is deprecated all the same.

Here is the offical AudioProcessEvent spec: https://webaudio.github.io/web-audio-api/#the-audioprocessingevent-interface-deprecated

If the line in question isn't needed of course we can remove it (we need to test regular loading and loading of decoded buffers)

Also the original commit where this came from https://github.com/katspaugh/wavesurfer.js/commit/8cedc6b649c9c1a261e1c6711ed5afaf866b3bb2 fixed this issue https://github.com/katspaugh/wavesurfer.js/issues/170 – maybe this helps us understand it a little better @katspaugh @thijstriemstra
