### ISSUE TITLE
Vertical Track

### ISSUE THREAD

**Issue by elBarkey** [katspaugh/wavesurfer.js#634]
Hi, is it possible to display the waveform in vertical layout ?
i've tried using css transofrm 90deg to parrent element, and it works.
but that just rotating the parrent element to 90 degrees, that's all. offcourse mouse event, seeking etc on actual waveform  doesn't work by just doing "css hacks".
is there any workaround on this?

**Comment by katspaugh** [comment]
Hi! Interesting question!

I think this function needs to be modified: https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.js#L41-L45

It assumes the horizontal axis. Try changing it to take `clientY` instead of `clientX`, `bbox.top` instead of `bbox.left` etc.

Also make sure you set the right rotation origin in CSS.

**Comment by elBarkey** [comment]
Thanks @katspaugh !
I followed your direction, it now works as as expected.
The only problem remains is, the rotated wrapper draws the width depends on its parent width.
can you point me to the width value origins ? so i can take its parent height instead of the width.

**Comment by katspaugh** [comment]
The container's width is used in these places: https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.js#L96
https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.js#L102
https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.js#L105
https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.js#L130
https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.js#L168

I'm not sure if *all* of these places need to be changed to `height`, though.

**Comment by elBarkey** [comment]
yep, you're right.
that way, the main  drawer core will be messed up.
as a solution i do this to get the the wrapper displayed vertically:

```html
<style>
    #v-container{
        position: fixed;
        top: 0px;
        left: 0px;
        height: 100%;
    }
    #w-container{
        transform: translateX(100%) rotate(90deg);
        transform-origin: top left;
    }
</style>
<div id="v-container">
    <div id="w-container">
        <div id="wave"></div>
    </div>
</div>
```

and change the wrapper parent height on ready event:

```javascript
wavesurfer.on('ready',function(){
    $('#w-container').width($('#v-container').height());
});
```

anyway, thanks for the kind response ;)

**Comment by katspaugh** [comment]
Cool, nice hack!

**Comment by 987123879113** [comment]
4 years later... (sorry for the necro)

I stumbled on this because I wanted to use wavesurfer.js in the same way. More specifically in my case, I want the very bottom to be the starting position and have it scroll upward. I'm not sure what I did wrong or if something just fundamentally changed with the library itself, but I couldn't get the above solution to work so I tried out a new approach.

Here's my solution for anyone else who stumbles on this and wants to do a vertical wavesurfer.js as well. This is using Vue.js, but it's possible to rewrite using vanilla JS too.

Note: This assumes you are fine with disabling interactions.

HTML:
```html
<div id="waveform" ref="waveform" @click="waveformOnClick"></div>
```

CSS:
```sass
  #waveform {
    transform: translateY(100%) rotate(-90deg)
    transform-origin: 50% 50%
  }
```

Javascript:
```javascript
      this.wavesurfer = WaveSurfer.create({
        container: '#waveform',
        interact: false
      })
...
      waveformOnClick (event) {
        var rect = this.$refs.waveform.getBoundingClientRect()
        var offset = rect.bottom - event.y
        var seekPosition = Math.max(0, Math.min(offset / rect.height, 1))
        this.wavesurfer.seekTo(seekPosition)
      },
```

Explanation: I disabled interactions and created a custom click handler. In the click handler, I translate the click at the Y position to the seek position and manually call `seekTo`. Visually, it behaves similar to letting wavesurfer.js handle the click. I think the code could probably be improved, but it works well enough to start prototyping out the rest of my program. You can adjust the math if you would prefer seeking from the top to bottom but the idea is the same.

I am not sure what else would be disabled when disabling interactions so ymmv. A quick grep suggests maybe the minimap plugin interactions?

Hope this helps someone out.

**Comment by thijstriemstra** [comment]
wavesurfer.js v4.7.0 added support for this, see example: https://github.com/katspaugh/wavesurfer.js/tree/master/example/vertical
