### ISSUE TITLE
Feature request: shortcode to disable the stop button, timecode fields, and wave pattern if we just need a play button sometimes.

### ISSUE THREAD

**Issue by a4jp-com** [katspaugh/wavesurfer.js#647]
Feature request: shortcode or a function to disable the stop button, timecode fields, and wave pattern if we just need a play button sometimes.

This plugin is great but sometimes I just need the play button.

Like at the bottom of this page:
http://agreatdream.com/grammar-past-tense/

If people can see the wave pattern only on this page it makes it easy to guess the answers.

It would also be cool if we could change the text of the play and stop button through a settings area. I just want to show the play, pause and stop icons without the English words on some sites if possible.

Hope you like the site I'm making too.
I will try to put sound files next to all the Japanese words too on the Japanese vocab pages.

**Comment by katspaugh** [comment]
This request is again for the WordPress plugin by @X-Raym.

Personally, I would suggest simply hiding the unused buttons via CSS:
```
<style>
.wavesurfer-stop, .wavesurfer-time, wavesurfer-duration {
  display: none;
}
</style>
```

**Comment by X-Raym** [comment]
@a4jp-com 
hi,
1. Choose the icon only theme so that language is not a problem OR Customize the translation with LocoTranslate plugin (useful for visual impair users)
1. Use CSS to hide unwanted elements
1. If you have a problem concerning the WordPress integration, please go the WordPress support forum.

@katspaugh Sorry ^^
