### ISSUE TITLE
Spectogram plugin cuts out half of the canvas

### ISSUE THREAD

**Issue by adw1n** [katspaugh/wavesurfer.js#702]
I noticed it when working with 44.1kHz files (in your examples you are using 22k ones and it works just fine).
This is what I get:
![spectogram_wavesurfer_half](https://cloud.githubusercontent.com/assets/8993001/14758001/2154aea0-08fa-11e6-9e0d-8c58affd95a4.png)
this is the same file in audacity (notice the 0-11k range):
![spectogram_audacity_11k](https://cloud.githubusercontent.com/assets/8993001/14758012/444a02e8-08fa-11e6-945e-7fcc1ce9b8c9.png)
this is the same file in audacity with range 0-22k
![spectogram_audacity_22k](https://cloud.githubusercontent.com/assets/8993001/14758022/58777746-08fa-11e6-9bae-b4466777d531.png)

I changed line 46 in wavesurfer-js/plugins/wavesurfer/spectogram.js (granted this breaks things for 22k files and most likely in other cases)
from: `this.height = this.fftSamples/2;`
to:
`this.height = this.fftSamples;'`
and I got as a result:
![spectogram_wavesurfer_full](https://cloud.githubusercontent.com/assets/8993001/14758040/8cb5bacc-08fa-11e6-80ee-ba34102efe0b.png)

my code:

``` <html>
<head>
  <script src="wavesurfer.js/dist/wavesurfer.min.js"></script>
  <script src="wavesurfer.js/plugin/wavesurfer.spectrogram.js"></script>
</head>
<body>
<div id="waveform"></div>
<div id="wave-spectrogram"></div>
<script type="text/javascript">
var wavesurfer = WaveSurfer.create({
  container: '#waveform',
});
wavesurfer.on('ready', function () {
    var spectrogram = Object.create(WaveSurfer.Spectrogram);
    spectrogram.init({
        wavesurfer: wavesurfer,
        container: "#wave-spectrogram",
    });
});
wavesurfer.load('music_file.mp3')
</script>
</body>
</html>
```

music file that I used: https://github.com/arirusso/d3-audio-spectrum/blob/master/public/media/sweep.mp3

**Comment by adw1n** [comment]
Please also check 8kHz files - canvas is at least twice too big.

**Comment by katspaugh** [comment]
@fzyukio is there a parameter to choose 44 kHz vs 22 kHz?

**Comment by fzyukio** [comment]
@adw1n `this.height = this.fftSamples/2` is correct. @katspaugh the frequency is associated with each audio file so it is not a parameter to chose. FFT returns a symmetric representation of a signal, half of all FFT bins is negative frequency, which is the mirror version of the other half. The spectrogram only contains positive frequency, hence its width is half the number of FFT bins (fftSamples). So setting `this.height = this.fftSamples` is mathematically wrong. The problem if any lies elsewhere. I'll test your code and get back later.

**Comment by adw1n** [comment]
@fzyukio but you are setting heightFactor to 2 in drawSpectrum (i'm working with mono files) which makes the effective height this.fftSamples/4 (only this.fftSamples/4 values get drawn for each bucket).

**Comment by adw1n** [comment]
Could you also explain why wavesurfer.backend.buffer.sampleRate==44100 for all files (tested on 8k, 22k, 44k)? http://wavesurfer-js.org/example/spectrogram/ soxi output:
```
Input File     : 'demo.wav'
Channels       : 1
Sample Rate    : 22050
Precision      : 8-bit
```

**Comment by thijstriemstra** [comment]
is this still an issue?

**Comment by adw1n** [comment]
@thijstriemstra yup - http://public.adw1n.com/wavesurfer.js-issue-702/

**Comment by thijstriemstra** [comment]
> Could you also explain why wavesurfer.backend.buffer.sampleRate==44100

I think it grabs the browser default, which is 44100 afaik.

**Comment by thijstriemstra** [comment]
maybe we should use an external spectrogram library for this plugin instead, e.g. https://github.com/vlandham/spectrogramJS

**Comment by shershey** [comment]
My coworker came across this bug report when he searched around after we discovered that the spectrogram frequency content was mislabeled and half of what we expected it to be. To demonstrate what I was seeing, we replaced the demo.wav file with a file that contains a 4kHz square wav (wav file with 16kHz sampling rate) and this is what I saw:

<img width="1006" alt="4khz wave displayed incorrectly" src="https://user-images.githubusercontent.com/2159220/58295211-0a23cf80-7d9c-11e9-8ed4-2926da614b8a.png">

Notice that the fundamental frequency is incorrectly labeled at 8kHz.  Changing the heightFactor = 1 fixed things.  I also specified an audioContext with "audioContext: new AudioContext({sampleRate: 16000})". This proved important when displaying waveforms with more frequency content if their sampleRate was low since the default audioContext seems to resample things pretty high (44.1 or 48kHz) and this results in a lot of black space at the top of the spectrogram.  This is the result with the changes:

<img width="942" alt="4khz wav displayed correctly" src="https://user-images.githubusercontent.com/2159220/58295220-0f811a00-7d9c-11e9-9bd9-e38673ff9d37.png">

Notice that the original demo.wav file has a sample rate of 22050hz and yet the demo implies there is frequency content above nyquist.

The issue appears not to be with the FFT/spectrogram but with that heightFactor. Does anybody know why it was originally set to something other than 1? 

In an ideal world the spectrogram plugin could determine the original sampling rate and so something with that information (such as create an audioContext with the same sampling rate) so that it doesn't resample and create that empty space, but I guess in the case of compressed audio this might be trickier.

Without understanding what the heightFactor is for, I wonder if it can be removed. I guess that would change the look of everyone's spectrograms if they're used to seeing only half of the spectrogram Thoughts? Alternatively, assuming heightFactor has a useful purpose, could we make it explicitly programmable in the Spectrogram's params?

**Comment by shershey** [comment]
After discussing this with a coworker, we were realizing that it would probably be better to leave the audioContext untouched, remove the heightFactor, and change the sampleRate of the offlineAudioContext to 16kHz and have that be a parameter that can be overidden. I can create a pull request to demonstrate what I mean.

**Comment by thijstriemstra** [comment]
> I guess that would change the look of everyone's spectrograms if they're used to seeing only half of the spectrogram

we're about to release 3.0 and breaking changes can still be made (if reasonable of course).

**Comment by shershey** [comment]
In discussing this with a coworker, we realized a better solution might be:

1) Remove heightFactor.
2) Modify the spectrogram to generate an offlineAudioContext with a sampleRate provided in the spectrogram's params. (using a different offlineAudioContext would allow for different sampleRates between playback and generating the spectrogram).
3) Give this a smaller default of something like 16kHz (So that by default any audio above a 16kHz sample rate will not have blackspace at the top of the spectrogram). 

I'm not sure how much extra work it would be to create a different offlineAudioContext for the spectrogram than for playback. I could look into it.

**Comment by thijstriemstra** [comment]
maybe using a 3rd-party plugin for the spectogram so we don't need to maintain that code, e.g. https://blog.freifunk.net/2017/06/26/choosing-spectrogram-visualization-library-javascript/

**Comment by shershey** [comment]
Using a well supported spectrogram library sounds like a good idea. My hacky fix for my use case will be to provide an audioContext with a sampleRate twice my actual sampleRate.

**Comment by thijstriemstra** [comment]
hopefully you can work on a PR for this, I'll happily review it and provide feedback.

**Comment by shershey** [comment]
With the realization that I can work around this issue by setting the AudioContext SampleRate it reduces my need for a fix. But I can spend some time on this to see how much work it would take me and, if it's reasonable, send out a PR.

**Comment by thijstriemstra** [comment]
@shershey maybe a fix would be properly documenting that behavior in the source code as well as the example?

**Comment by shershey** [comment]
@thijstriemstra what's the timeline for the 3.0 release?

**Comment by thijstriemstra** [comment]
don't know. when it's done it's done.

**Comment by maxammann** [comment]
I just tried to create a spectrogram of a 16000Hz audio file. The max frequency in the spectrogram was 44100. 

I fixed this by using `audioContext: new AudioContext({sampleRate: 16000})`.
