### ISSUE TITLE
iOS w/ MediaElement (double click and slower)

### ISSUE THREAD

**Issue by eduzaka** [katspaugh/wavesurfer.js#740]
Hi, first of all congratulations, this is really good.

We are looking info but we didn't find what's the way to make it working on iOS with MediaElement. We think the problem is the autoplay not accepted on iOS, but other audio players work like a charm (without waveforms) in iOS without autoplay, can we make some code to solve it?

When we click on track, it loads very slowly (not like desktop) and later we have to click again to make it sound.

**Comment by katspaugh** [comment]
What are this other players? We could look at their source code and see how they work around the iOS limitations.

Regarding slowness, it's because it downloads the file via AJAX, decodes the binary into a JavaScript array and then draws a waveform from this array. I wouldn't be surprised it to be slower on mobile devices. You may want to use a pre-decoded waveform array. See https://github.com/katspaugh/wavesurfer.js/blob/master/example/audio-element/main.js#L26-L28

**Comment by eduzaka** [comment]
Hey, thanks for the quick reply.

We are using prerendered peaks with a JSON data, in the desktop it loads perfectly but mobile loads it slowly. BTW, the first click loads peaks and the second click plays audio.

We bought some other players time ago, for example: http://codecanyon.net/item/html5-audio-player-with-playlist/1694831

We need something like this, but with waveform (like wavesurfer)... we are looking to mix both, but maybe there are other solution.

**Comment by entonbiba** [comment]
@eduzaka please test using latest version, performance has improved significantly since this ticket.

reopen is issue still persists.
