### ISSUE TITLE
Check memory consumption with multiple instances of wavesurfer.js

### ISSUE THREAD

**Issue by katspaugh** [katspaugh/wavesurfer.js#77]
Need to verify, that the memory is released after each successful `decodeAudioData`.

**Comment by k-bx** [comment]
I see a memory consumption problem with Wavesurfer on Firefox (Ubuntu 18.04). Every time I reload a tab I get another 400 MB consumed. Arguably, the file is 65 MB, and probably it's Firefox who needs to be blamed for not releasing the memory on tab reload, but I just wanted to mention the issue here.

**Comment by Zegorax** [comment]
I have exactly the same issue as @k-bx but using Safari 13.1
