### ISSUE TITLE
[timeline] Multicanvas Timeline Zoom Scrolling Issue

### ISSUE THREAD

**Issue by samedayjeremy** [katspaugh/wavesurfer.js#778]
When scrollParent is initially set to false, then the user zooms, the timeline will not scroll with the waveform. Even if the params.scrollParent is explicitly set to true at that point with code.

It would be nice to be able to see the entire waveform (scrollParent = false) initially, then have the timeline be scrollable along with the waveform when zooming.  This worked with the non-multicanvas timeline renderer but has since broken due to this pull request.
[https://github.com/katspaugh/wavesurfer.js/pull/765#issuecomment-231247869](url)

**Comment by chrisparton1991** [comment]
I'll try and take a look at this tonight.

**Comment by jeremylach** [comment]
It seems that this line is not doing anything

```
//From updateScroll in wavesurfer.timeline.js
this.wrapper.scrollLeft = this.drawer.wrapper.scrollLeft;
```

The drawer.wrapper.scrollLeft property updates as it scrolls but the wrapper.scrollLeft value remains 0

**Comment by chrisparton1991** [comment]
That's correct @jeremylach. The (main) issue was that the canvases weren't being reallocated upon zoom, so the zoomed timeline was drawn to the first canvas, but there were no other canvases available. The scrollLeft wasn't updating because there was no scrollable content.

I also fixed a couple of other issues to do with canvas positioning and sizing. Can you please take a look at the attached 
[timeline-scroll-fix-test.zip](https://github.com/katspaugh/wavesurfer.js/files/412482/timeline-scroll-fix-test.zip) and let me know if it works for you?

If so, I'll raise a PR with the fixes.

**Comment by jeremylach** [comment]
It is working great!! This also fixed another issue where timeline numbers were overlapping if the wavesurfer was zoomed in far and scrolled through for a while.  

Thanks for your work.

**Comment by chrisparton1991** [comment]
Awesome, I'll raise a PR shortly. Yeah, that overlap issue was one of the other things I found. I had a dodgy length calculation for the last canvas that didn't take into account the scroll width of the container.

Apologies for causing the issues in the first place :) I think once this and the other PR are merged in, MultiCanvas will be free of known issues!

**Comment by chrisparton1991** [comment]
PR raised @jeremylach, #792.
