### ISSUE TITLE
Export frame as image

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#822]
An `exportImage` method that returns image data (png, etc) for the current wavesurfer frame would be useful.

**Comment by thijstriemstra** [comment]
it would be good to have a `getImage` implementation for `drawer.multicanvas.js` as well. @chrisparton1991 can you take a look at that?

**Comment by chrisparton1991** [comment]
@thijstriemstra, I don't know how feasible it is to add this to MultiCanvas. I'd need to get the data URLs from each canvas and stitch them together.

I've done some googling, and it seems the way to do this is typically to redraw the data URLs from each canvas onto a separate canvas, then re-export that canvas as a data URL. However, since the point of MultiCanvas is to overcome the size limitations of a single canvas, there wouldn't be much benefit to doing this. Thoughts?

**Comment by katspaugh** [comment]
Since it would be good to, at some point, make MultiCanvas the default and remove the single canvas, I think the algorithm should be the same for both backends:
 * Check the size.
 * If the size is greater than a single canvas can handle, downscale.
 * Draw on a single canvas.
 * Export.

**Comment by thijstriemstra** [comment]
It sounds like things will get a lot more complicated when MultiCanvas is introduced as the default, but I could be wrong. Maybe this ticket should be closed and a future ticket can introduce `getImage` support for multi-canvas.

**Comment by usfslk** [comment]
Hi, on wavesurfer docs there's exportImage(format, quality, type) can you please shed a light on those 3 parameters? I'm not sure what values I should use

**Comment by thijstriemstra** [comment]
@usfslk read the docs at https://wavesurfer-js.org
