### ISSUE TITLE
Success with Cross-Origin Resource Sharing and S3?

### ISSUE THREAD

**Issue by ghost** [katspaugh/wavesurfer.js#83]
Has anyone had success using wavesurfer.js to reference an audio file hosted on AWS/S3 using Cross-Origin Resource Sharing (CORS)?

http://aws.amazon.com/about-aws/whats-new/2012/08/31/amazon-s3-announces-cross-origin-resource-sharing-CORS-support/

We're hosting wavesurfer.js on our domain and trying to point to audio on S3 and are getting "Access-Control-Allow-Origin" errors. Before I see if the owner of the S3 bucket is willing to go through the steps in the linked article, I'm curious if it worked for anyone else.

**Comment by manjurs89** [comment]
I had same problem while uploading the files to s3 bucket.. I changed the bucket policy and CORS configuration then everything worked fine.

**Comment by itsmrwave** [comment]
CORS isn't an issue with wavesurfer.js ... since it's really about how your S3 bucket has been configured.  Apply a CORS config as @mattbryson has suggested.

FWIW ... I've been able to implement this even using Cloudfront as the CDN (on top of S3).

**Comment by james-hoegerl** [comment]
@itsmrwave I'm not sure how you can say its not a waversurfer.js issue. Isn't chrome blocking the request from the start, not AWS S3? Also could you possibly expand on how you implemented waveform.js with Cloudfront and S3? I really would love to use waveform.js but I'm stumped on how to configure it to work with S3 storage.

Thanks

**Comment by itsmrwave** [comment]
@james-hoegerl It's not a waversurfer.js issue because browsers block requests to some resources from sources that have not listed the client accessing in the list of clients allowed to access. [From Wikipedia ...](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)

> A web page may freely embed images, stylesheets, scripts, iframes, videos and some plugin content (such as Adobe Flash) from any other domain. However embedded web fonts and AJAX (XMLHttpRequest) requests have traditionally been limited to accessing the same domain as the parent web page (as per the same-origin security policy). "Cross-domain" AJAX requests are forbidden by default because of their ability to perform advanced requests (POST, PUT, DELETE and other types of HTTP requests, along with specifying custom HTTP headers) that introduce many cross-site scripting security issues.

Seems audio file also fall into the category of these resources since it is an AJAX request initiated by Wavesurfer. Therefore, this is really a problem caused by incorrect or lack of a CORS configuration. So ... to stop Chrome from blocking the request (or any other browser that exhibits this behaviour) you need to configure your source (i.e S3, Cloudfront) CORS config correctly.

Luckily both S3 and Cloudfront support CORS configuration :-) See [AWS S3 Enabling Cross-Origin Resource Sharing](http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) for the details.

If you enable CORS on the S3 bucket then Cloudfront (assuming S3 is the origin) will respect that config.

**Comment by james-hoegerl** [comment]
Thanks for the response. My S3 is configured to for CORS. I'm having an issue similar to @alexcasalboni has further up in the thread. I'm trying to stream from my origin "dev.com". and the AJAX request is being blocked by the browser. I guess I just misunderstood you. 

I suppose the proper answer is I either need a proxy or I can't use wavesurfer.js as was stated by @katspaugh further up in the thread.

Thanks for the help.

**Comment by james-hoegerl** [comment]
@Mattbryson did you ever find a solution?

**Comment by mattbryson** [comment]
@james-hoegerl Yeah, although can't quite recall what it was!  I think the issue might have been down to the URLS that we were using - you can access S3 files in 2 ways, either as virtual host, or path...

`http://bucket.s3-aws-region.amazonaws.com` or `http://s3-aws-region.amazonaws.com/bucket`

Our initial set up used the virtual host style and we had to change this to use the path style. I think that, in combination with the CORS set up solved the issues.

As I say it was a while ago, so might not have been just that.....

**Comment by itsmrwave** [comment]
@james-hoegerl I can confirm that this works. I have set this up recently and it's working properly even now. Like @mattbryson, it's been a few months so I might have forgotten some implementation details.

One **gotcha** that I can remember is that you have to configure Cloudfront to pass the CORS headers from S3. Configuring S3 only would work if accessing S3 directly ... because you see, Cloudfront makes the request to the object on S3 for you and so picks up some headers and also discards some. It could be that you haven't configured Cloudfront and so ... while S3 sets the CORS headers, Cloudfront discards them? I'm guessing here.

And I quote ...

> If you enabled cross-origin resource sharing (CORS) on an Amazon S3 bucket or a custom origin, you can configure CloudFront to respect the CORS settings. Configure CloudFront to forward a whitelist of headers and include the applicable headers in the list of headers to forward, depending on whether you're using Amazon S3 or a custom origin:

> Amazon S3

> * When you want OPTIONS responses to be cached, configure CloudFront to forward the following headers: Origin, Access-Control-Request-Headers, and Access-Control-Request-Method.
> * When you don't want OPTIONS responses to be cached, configure CloudFront to forward the Origin header. You can also configure CloudFront to forward Access-Control-Request-Headers and Access-Control-Request-Method headers, but it's not required.

See below how you whitelist CORS headers on Cloudfront ...

<img width="856" alt="screen shot 2015-08-24 at 12 17 27 pm" src="https://cloud.githubusercontent.com/assets/703786/9437903/274bd388-4a5a-11e5-921b-2bd331aa4cd4.png">

Learn more about [this behaviour here][1].

_Ps: By virtue of Cloudfront being CDN there's a lot of caching. Sometimes you have to force reload or invalidate objects._

_Ps 2: You may email me privately with questions._

[1]: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/header-caching.html#header-caching-web-cors

**Comment by james-hoegerl** [comment]
Thanks for all the help @mattbryson and @itsmrwave. Much appreciated. Sorry @katspaugh for mucking up this issue with comments a bit off topic. I'm going to look into the last couple posts and hopefully get waveform.js working for my startup.

**Comment by itsmrwave** [comment]
@james-hoegerl No problem. I think the conversation here is still helpful to those looking into implementing Wavesurfer and are having CORS issues. You may email me with specific questions ... especially about S3 & Cloudfront since the main issues around CORS are covered already (and which should remain as the focus of the thread). All the best.

_Ps: Email is on my profile._

**Comment by james-hoegerl** [comment]
Just like to finalize this discussion by saying I got it working completely fine with S3. The issue was so silly. The CORS configuration for each bucket under S3 -> Bucket -> Properties -> Permissions -> Edit CORS Configuration is pre filled with a standard CORS config which had me assuming that it was already configured for that and it simply wasn't working. 

Stupidly enough that is just pre generated text and you must click the "Save" button to actually apply the config.

This can be seen here. http://stackoverflow.com/questions/17533888/s3-access-control-allow-origin-header

In the last commentor.

wavesurfer working like a dream.

Thanks again @itsmrwave @mattbryson.

**Comment by alimaserrat** [comment]
I'm using W3 Super Cache plugin of Wordpress, and I have enabled the CDN option that is sync the file with S3 of amazon, however i'm getting:

by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 


I don't know what CORS option should be added to Amazon priviallage, i have tried few different ones but nothing is helping..


It is loading all the files except the fonts and one gif file.

**Comment by huangfh** [comment]
> Nothing, and it's actually not possible to manually set the `Origin` request header (it makes sense, since it's a security policy managed by the browser itself!).
> 
> So it looks like I can't use wavesurfer with the streaming URL I have, even though it perfectly works when I use it with a native `<audio>` element. Isn't there a way to avoid the explicit ajax call and still use the wavesurfer library as for waveform visualization? (note: the streaming server is given by an external service, so I can't deal with the response headers)

have you sloved it ?

**Comment by sunguosu** [comment]
> > Nothing, and it's actually not possible to manually set the `Origin` request header (it makes sense, since it's a security policy managed by the browser itself!).
> > So it looks like I can't use wavesurfer with the streaming URL I have, even though it perfectly works when I use it with a native `<audio>` element. Isn't there a way to avoid the explicit ajax call and still use the wavesurfer library as for waveform visualization? (note: the streaming server is given by an external service, so I can't deal with the response headers)
> 

@alimaserrat have you has any ideas?

**Comment by jamesryan-dev** [comment]
Correct CORS config should be JSON

```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD",
            "PUT",
            "POST"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "MaxAgeSeconds": 3000
    }
]
```
