### ISSUE TITLE
Large MP3 files cause DOM Exception 12 

### ISSUE THREAD

**Issue by vernondegoede** [katspaugh/wavesurfer.js#9]
Hi there,

I absolutely love this plugin. It works great when I try to play small MP3 files.

However, when I try to load a larger MP3 file (51 MB), I get an JS error: DOM Exception 12. 
The MP3 file seems to load fine in the beginning, but in the end it's slowing down (the line which indicates that it's loading moves at a much slower rate). My Chrome browser tab also crashes at the end (gives me a purple error message). 

This is the error I'm getting:

``` javascript
Uncaught Error: SyntaxError: DOM Exception 12 webaudio.js:66
WaveSurfer.WebAudio.loadData webaudio.js:66
(anonymous function)
```

When I'm looking at webaudio.js it seems to be an issue with the decodeAudioData() method.

Is this a known issue? And how can I fix this problem?

Help would be appreciated, since I'm stuck with my project right now.

Thanks in advance!

**Comment by chinshr** [comment]
Instead of starting a new thread on streaming audio, AFAIK, this thread is the most appropriate to propose the idea of using [m3u playlists](http://www.boutell.com/newfaq/creating/playlist.html) that essentially works like streaming audio, or consecutively playing smaller mp3 files. I am pre-generating the waveform (JSON) ahead of time, so it would be great to have a way to play `.m3u` files in wavesurfer.js. Would love to hear your thoughts and if this could solve your problem?

**Comment by kavishatalsania** [comment]
Does anyone found a solution for this? I am also facing the same issue.
