### ISSUE TITLE
Limit playback to part of a file

### ISSUE THREAD

**Issue by davidorme** [katspaugh/wavesurfer.js#928]
I'm working on a project where I want users to be able to create and annotate regions of an audio file. The annotations tool is working fantastically for identifying the regions. I then want to be able to provide a separate page that isolates that region of the audio in a player and provides an interface for commentary. 

Ideally, it would be good only to load that region of the file in the first place - regions are typically only a few seconds long, so loading the whole file (~ 5 minutes) uses unnecessary bandwidth. I'd rather not have to create physical audio files for each separate region.

Failing that, is there a way to limit which region of the audio is displayed?

Many thanks for the fantastic code,
David

**Comment by mspae** [comment]
I can't think of a way of playing/rendering only part of a file. However, the file should not be loaded multiple times once your browser has downloaded it (because of browser cache) – You could even cache the peaks of the decoded file into f.x. `localStorage` and then pass them explicitly to the loading call on any subsequent page loads to speed up rendering.

**Comment by entonbiba** [comment]
@davidorme you can achieve this with php or nodejs. 

I would create an api that sends back parts of the audio file based on the parameters that have been requested. It also allows you to use the full audio file without creating multiple files per region.

This saves bandwidth, since it you do extract parts through the browser it will have to download the full audio file. You can use caching but that still means downloading the full audio file at least once.

For php the getid3 library can be used. I can probably put together a sample using this library with a custom api script sometime soon.
http://getid3.sourceforge.net/

**Comment by mspae** [comment]
I mean it kind of depends on your use case. If a user is only ever interested in 20 seconds and absolutely never in the rest of the audio file then of course it makes sense to split. But if the regions are actually just a kind of zoom-in to a specific highlighted part then maybe not.

**Comment by davidorme** [comment]
The file size is somewhat under our control - they're recorded as long (1 hour +) lossless files but we were planning to serve them up as 5 minute chunks without super high quality (current samples are 64 kbps, 24 kHz and about 2.4 Mb).

The use case will typically be that someone loads the whole 5 minute clip and listens to it but then might want to focus in on particular regions - the point is to demarcate and identify animal calls within the recording. I want to present the call region on a separate URL as cleanly as possible: ideally a waveform that just covers the call and which can load just that call. It is very possible that users might come directly to the call region page without having been to the whole source, so it wouldn't necessarily be in cache.

I'm using web2py and python  - so a python API that rips the sample from the bigger file and sends that back as a temporary file might work, as long as it is a reasonably speedy operation on the server side. It might be easier to create static files!

**Comment by entonbiba** [comment]
@davidorme you can also make the api check and generate smaller files if they don't exist based on the parameters, if they do it will send back the available static file instead. Ideally the files should be put into a CDN when generated. This type of setup would save bandwidth and make it fast to load.

**Comment by entonbiba** [comment]
@davidorme this would make more sense with hls audio #1078 

also have a look at this sample see if it works for you
https://github.com/katspaugh/wavesurfer.js/issues/2058#issuecomment-761284236
